name: 自动签到海绵联机

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 17 * * *' # 每天一次，UTC 时间 17 点运行（即北京时间 1 点）
  workflow_dispatch:

jobs:
  read-and-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 海绵联机签到
      env:
        HMLJ_USERPASSWD: ${{ secrets.HMLJ_USERPASSWD }}
      run: |
        IFS=',' read -r -a upds <<< "$HMLJ_USERPASSWD"

        for upd in "${upds[@]}"; do
          curl -s -c "ck.hmlj" -X POST "https://www.yunmc.vip/login?action=email" -d $upd
          response=$(curl -s -b 'ck.hmlj' 'https://www.yunmc.vip/addons?_plugin=points_mall&_controller=index&_action=sign' -X 'POST' -H 'x-requested-with: XMLHttpRequest')
          rm -rf ck.hmlj
          if echo "$response" | grep -q '"code":1'; then
            echo "签到成功"
          else
            echo "内容返回 : $response"
          fi
        done
